### ISSUE TITLE
Contribution list 

### ISSUE THREAD

**Issue by devmsh** [laracademy/interactive-make#11]
like the package, and I want to contribute on it, here is a list of suggested contributions

- [ ] support nested resource controller generation
- [ ] support "event:generate" as a top level command, or as a suggestion question in the event or handler make commands.
- [ ] add extra command than the official one, specially for tasks like "make:component" for generation vue component.
- [ ] check if developer install common 3rd party generator like [Laravel-5-Generators-Extended](https://github.com/laracasts/Laravel-5-Generators-Extended) and support there features

If any of these contribution fit with your plan, I will be happy to submit a PR to support any of them ;)

**Comment by ruchernchong** [comment]
>add extra command than the official one, specially for tasks like "make:component" for generation vue component.

It is a good idea, but I think this package is just going to limit to exclusively Laravel only.

**Comment by devmsh** [comment]
@ruchern , did you mean the official artisan command only? when suggest the make:component because laravel came with vue as default, and it will support react in the next release, so we can use the Example.vue and convert it to stub and generate new .vue files quickly. 

What about other items?

**Comment by ruchernchong** [comment]
I don't know. I just feel like this interactive make command should not include generating Vue components.

**Comment by michael-mcmullen** [comment]
I would like to stick to the functionality that is offered inside of Laravel. I don't have any issue with adding something like that into the generator however, I just don't feel that is the direction this command will go.

But if it is a default in Laravel then it can definitely be added.
