### ISSUE TITLE
The switch for unit tests does not work

### ISSUE THREAD

**Issue by troccoli** [laracademy/interactive-make#13]
When I try and make a test the script asks me whether it's a unit test or not. This is, I guess, to know whether to use the --unit flag in the make:test artisan command.

However, this does not work. Whatever I answer to that question, the new test is always created in app/test/Feature. I'm using version 0.9

**Comment by michael-mcmullen** [comment]
Hi @troccoli 

Thanks for pointing that out, in a few minutes packagist should have the latest version which includes the fix. So you can just update from there.

**Comment by troccoli** [comment]
Excellent. Thank you.
