### ISSUE TITLE
make:model is not creating controller or migration

### ISSUE THREAD

**Issue by kskrlin** [laracademy/interactive-make#15]
` What command are you running?:
  [auth        ] Auth
  [controller  ] Controller
  [command     ] Command
  [event       ] Event
  [job         ] Job
  [listener    ] Listener
  [mail        ] Mail
  [middleware  ] Middleware
  [migration   ] Migration
  [model       ] Model
  [notification] Notification
  [policy      ] Policy
  [provider    ] Provider
  [request     ] Request
  [seeder      ] Seeder
  [test        ] Test
 > model

 Model Name (Example: Posts):
 > Order

 Do you want to make a migration for this model? (yes/no) [no]:
 > yes

 Do you want to make a controller for this model? (yes/no) [no]:
 > yes

 Is this controller a resourceful controller? (yes/no) [no]:
 > no

Model created successfully.`

After this snippet of commands in terminal only model App\Order is created, no migration or controller were created.
However, when I go with command "controller" both controller and model are created successfully and for the migration I need to user migration command. Why the make:model approach is not creating controller or migration?

**Comment by ruchernchong** [comment]
<img width="1280" alt="screen shot 2017-06-17 at 6 56 40 pm" src="https://user-images.githubusercontent.com/10343662/27252345-bd278f34-538e-11e7-95f1-236d218bbae5.png">

It is working for me. Try clearing composer's cache and reinstalling the packages.

**Comment by michael-mcmullen** [comment]
@kikky7 what version of laravel are you using?

**Comment by kskrlin** [comment]
Still didn't test with this solution above.

I am using 5.4 version.

**Comment by kskrlin** [comment]
Clearing composer's cache didn't help.

It is working now, but after I removed the package and installed it again.
Maybe the issue was I was using 0.8 version, and the current version is 1.1
