### ISSUE TITLE
Laravel 6

### ISSUE THREAD

**Issue by IndexZer0** [laracademy/interactive-make#31]
Used this package for a long time. It hasn't worked with Laravel 6 and I miss it.

Any plans to support Laravel 6?

php artisan make
> migration
Table Name (Example: users):
> test
Are you creating a new table (yes/no) [no]:
> no
Setting table option for table test

In MakeCommand.php line 225:

  Trying to access array offset on value of type null

**Comment by michael-mcmullen** [comment]
I will pull it into a brand new branch this weekend and fix any issues that come up (like the one you posted)

**Comment by IndexZer0** [comment]
Thanks for that.

This would be a great addition to laravel framework core. It boggles my mind why laravel hasn't adopted this.

**Comment by michael-mcmullen** [comment]
Try out the latest package (running an update should grab 1.4)

**Comment by IndexZer0** [comment]
Thanks, working for the above example.
