### ISSUE TITLE
Command "make" is not defined.

### ISSUE THREAD

**Issue by ellisfan** [laracademy/interactive-make#6]
in laravel 5.4.21

[Symfony\Component\Console\Exception\CommandNotFoundException]  
Command "make" is not defined.                                  
Did you mean one of these?

**Comment by michael-mcmullen** [comment]
Did you add the `serviceprovider` into `config/app.php`?

Should look something like this

```
    'providers' => [

        /*
         * Laravel Framework Service Providers...
         */
        // ... regular providers
        
        /*
         * Package Service Providers...
         */
        Laravel\Tinker\TinkerServiceProvider::class,
        Laracademy\Commands\MakeServiceProvider::class, // <-- right here

        /*
         * Application Service Providers...
         */
        // application providers
```

**Comment by ellisfan** [comment]
@tutelagesystems yes, i have added the serviceprovider into app.php
i try to restart php and run composer dump-autoload but it was useless

**Comment by ruchernchong** [comment]
@Bantes Do you have an alias set for `php artisan` or any sort?

**Comment by michael-mcmullen** [comment]
@Bantes did you solve the issue at hand with @ruchern's question? This package is already setup for Laravel 5.5 where you do not need to add the provider into your application.

**Comment by ruchernchong** [comment]
@Bantes Oh yes. After each installation of php packages into `config/app.php`, it is best to do a `php artisan config:cache` and it should or most of the time, work.

**Comment by michael-mcmullen** [comment]
Old issue which the user has not came back to say if it was resolved or not.
